kind: pipeline
name: default
type: docker

steps:
# - name: npm-build
#   image: 'node:10.6.0'
#   commands:
#     - 'npm install'
#     - 'npm run build'
#   when:
#     branch: master

- name: docker-build
  image: docker:dind
  volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  settings:
    # insecure: true # 因为使用的是私有仓库，没有 https 支持，所以要设置成 insecure 才能连接
    dockerfile: Dockerfile # 使用 Dockerfile 的名字
    # repo: lsy272631750/test # 打包后 Docker 镜像的名字
    registry: https://hub.docker.com # 镜像仓库的地址
  commands: 
    - sleep 5
    - docker build --rm -t test_docker .
    - docker login --username=lsy272631750 --password=cptbtptp123
    - docker tag test_docker lsy272631750/test:test_docker
    - docker push lsy272631750/test:test_docker
  when:
    branch: master

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

- name: rancher-build
  image: peloton/drone-rancher
  url: 'http://39.105.44.242:9904/v1'
  key: ADFB50C778525A36194A
  secret: 7f6B9wJM2DmbcjMVH3u8Zei25Mh6oKEgSUDn5Zza
  service: test/testApp
  docker_image: 'lsy272631750/test:test_docker'
  start_first: false
  confirm: false
  timeout: 300 
  # depends_on:
  # - docker-build
  when:
    branch: master 

# services:
# - name: docker
#   image: docker:dind
#   privileged: true
#   volumes:
#   - name: dockersock
#     path: /var/run

# volumes:
# - name: dockersock
#   privileged: true
#   host:
#     path: /var/run/docker.sock

# volumes:
# - name: docker
#   host:
#     path: /var/run/docker.sock
# # services:
# # - name: docker
# #   image: docker:latest
# #   privileged: true
# #   volumes:
# #   - name: dockersock
# #     path: /var/run

# # services:
# # - name: docker
# #   image: docker:dind
# #   privileged: true
# #   volumes:
# #   - name: dockersock
# #     path: /var/run

# # volumes:
# # - name: dockersock
# #   temp: {}
# # steps:
#   # - name: build-master
#   #   image: 'node:10.6.0'
#   #   commands:
#   #     - 'npm install'
#   #     - 'npm run build'
#   #   when:
#   #     branch: master
# #   - name: public-online   
# #     image: plugins/docker
# #     volumes:
# #     - name: dockersock
# #       path: /var/run/docker.sock
# #     commands:
# #       - 'sleep 5'
# #       - 'docker --version'
# #       - 'docker login --username=lsy272631750 --password=cptbtptp123'
# #       - 'docker ps'
# #       - 'docker build --rm -t test_docker .'
# #       - 'docker tag test_docker lsy272631750/test'
# #       - 'docker push lsy272631750/test:test_docker'
# #     when: 
# #       branch: master  

# # volumes:
# #   - name: dockersock
# #     host:
# #       path: /var/run/docker.sock
# # services:
# #   - name: docker
# #     image: docker:dind
# #     privileged: true
# #     volumes:
# #   - name: dockersock
# #     path: /var/run
