kind: pipeline
type: docker
name: api
steps:
  - name: build-master
    image: 'node:10.6.0'
    commands:
      - 'npm --registry https://registry.npm.taobao.org install express'
      - 'cnpm install'
      - 'npm run build'
    when:
      branch: master
  - name: public-online   
    image: plugins/docker 
    commands:
      - 'docker login --username=lsy272631750 --password=cptbtptp123'
      - 'docker build --rm -t test_docker .'
      - 'docker tag test_docker lsy272631750/test'
      - 'docker push lsy272631750/test:test_docker'
    when: 
      branch: master  
  # rancher-online:
  #   image: peloton/drone-rancher
  #   url: 'https://rancher.11vx.cn'
  #   access_key: B24653F95507063ACE6A
  #   secret_key: seyTtWvHaAUXjuyQBxH5BarRXZcZDaKvb9epCZgM
  #   service: app/app1 
  #   docker_image: 'registry.cn-beijing.aliyuncs.com/my_docker_test_01/docker_test_02'
  #   start_first: false
  #   confirm: true
  #   timeout: 300 
  #   when:
  #     branch: master 