version: '3.7'
services:
  drone:
    image: drone/drone:2
    ports:
      - '9901:80'
    environment:
      - DRONE_SERVER_HOST=${your_host}
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=${your_rpc_secret}
      - DRONE_COOKIE_SECRET=e8206356c843d81e05ab6735e7ebf075
      - DRONE_COOKIE_TIMEOUT=720h
      # GitHub Config
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${your_github_client_id}
      - DRONE_GITHUB_CLIENT_SECRET=${your_github_client_secret}
      - DRONE_LOGS_DEBUG=true
      - DRONE_CRON_DISABLED=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_USER_CREATE=username:Blubiubiu,admin:true
    volumes:
      - ./data:/data
  runner:
    image: drone/drone-runner-docker:1.6.1
    environment:
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${your_rpc_secret}
      - DRONE_TMATE_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
